/**
 * This file was generated by the Jeddict
 */
package jpafinal.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author mrgum
 */
@Entity
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Street;

    @Basic
    private String City;

    @Basic
    private String Country;

    @OneToMany(mappedBy = "address")
    private List<SoccerPlayer> soccerPlayers;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Address() {
    }
    

    public Address(String Street, String City, String Country) {
        this.Street = Street;
        this.City = City;
        this.Country = Country;
    }
    

    public String getStreet() {
        return this.Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    public String getCity() {
        return this.City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getCountry() {
        return this.Country;
    }

    public void setCountry(String Country) {
        this.Country = Country;
    }

    public List<SoccerPlayer> getSoccerPlayers() {
        if (soccerPlayers == null) {
            soccerPlayers = new ArrayList<>();
        }
        return this.soccerPlayers;
    }

    public void setSoccerPlayers(List<SoccerPlayer> soccerPlayers) {
        this.soccerPlayers = soccerPlayers;
    }

    public void addSoccerPlayer(SoccerPlayer soccerPlayer) {
        getSoccerPlayers().add(soccerPlayer);
        soccerPlayer.setAddress(this);
    }

    public void removeSoccerPlayer(SoccerPlayer soccerPlayer) {
        getSoccerPlayers().remove(soccerPlayer);
        soccerPlayer.setAddress(null);
    }

}