/**
 * This file was generated by the Jeddict
 */
package jpafinal.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author mrgum
 */
@Entity
public class FootballClubb {

    @Id
    public String name;

    public FootballClubb() {
    }

    public FootballClubb(String name) {
        this.name = name;
    }

    
    @OneToMany(mappedBy = "footballClubb", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<SoccerPlayer> soccerPlayers;

  

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<SoccerPlayer> getSoccerPlayers() {
        if (soccerPlayers == null) {
            soccerPlayers = new ArrayList<>();
        }
        return this.soccerPlayers;
    }

    public void setSoccerPlayers(List<SoccerPlayer> soccerPlayers) {
        this.soccerPlayers = soccerPlayers;
    }

    public void addSoccerPlayer(SoccerPlayer soccerPlayer) {
        getSoccerPlayers().add(soccerPlayer);
        soccerPlayer.setFootballClubb(this);
    }

    public void removeSoccerPlayer(SoccerPlayer soccerPlayer) {
        getSoccerPlayers().remove(soccerPlayer);
        soccerPlayer.setFootballClubb(null);
    }

    public void add(FootballClubb footballClubb) {
    }

    public void setFootballClubb(FootballClubb footballClubb) {
    }

    public void remove(FootballClubb footballClubb) {
    }
    
    

}